name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun Install Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            bun-${{ runner.os }}-

      - name: Install Frontend Dependencies
        run: bun install --frozen-lockfile

      - name: Run Pint (PHP Style)
        run: vendor/bin/pint

      - name: Format Frontend (Write)
        run: bun run format

      - name: Lint Frontend
        run: bun run lint

      - name: Typecheck Frontend
        run: bun run types

      - name: Verify Formatting (Check)
        run: bun run format:check

      - name: Commit Style Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: chore: apply code style fixes (Pint/Prettier)
          commit_options: '--no-verify'
